### ISSUE TITLE
3D VOLUMES NOT AN ISSUE PER SEI rather a question.

### ISSUE THREAD

**Issue by Goitsemedi888** [Nischaydnk/RSNA-2023-1st-place-solution#1]
your work is brilliant. We wanted to use segments of your code to build a Vision Transformer (ViT) using transfer learning. We run into an issue with the code 

print("MAKING TOTAL-SEGMENTOR DATA")

meta = pd.read_csv(f'{PATHS.TOTAL_SEGMENTOR_FOLDER}/meta.csv', delimiter=';')
meta['abdomen'] = meta.study_type.apply(lambda x: 1 if 'abdomen' in x else 0)
meta = meta[meta['abdomen']==1].reset_index(drop=True)

SAVE_FOLDER = PATHS.TOTAL_SEGMENTOR_SAVE_FOLDER
os.makedirs(SAVE_FOLDER, exist_ok=1)

where is the meta.csv how is it generated.

Can we please have the meta.csv, 3d volume.npy  and the corresponding labelled csv

one of the issues in implementing a VIT is the 16x16 patch that is 3 layers. After the 3d volumes are created they are 32 layers

**Comment by HarshitSheoran** [comment]
When you download TotalSegmentor dataset from https://zenodo.org/records/6802614

After unzipping, In the folder "Totalsegmentator_dataset", there will be a meta.csv file

![image](https://github.com/Nischaydnk/RSNA-2023-1st-place-solution/assets/37008327/45d5d845-ee4a-4ce0-bbaf-9dfcd241354d)
