### ISSUE TITLE
Question about copy segmentation volume

### ISSUE THREAD

**Issue by powerLEO101** [Nischaydnk/RSNA-2023-1st-place-solution#2]
Thank you for your solution!

I have a small question about the data preprocessing for segmentation training. 

At line 150 in make_segmentatoin_data1.py, what is the purpose of copying the seg_volume? What would be the consequence if I did not perform .copy, since the other volume is not copied? 

seg_volume = seg_volume[np.arange(0, seg_volume.shape[0], 2)].copy()

https://github.com/Nischaydnk/RSNA-2023-1st-place-solution/blob/77ed554f80c626195d0e18adcd8a739b2a96ef86/Datasets/make_segmentation_data1.py#L150

**Comment by Nischaydnk** [comment]
Hi @powerLEO101 
Thanks for bringing it up. It shouldn't create any difference as we are overriding the same variable 'seg_volume'. you can remove .copy(). In earlier experiments we were trying out multiple ways to process seg_volume & used it for that purpose.
